### ISSUE TITLE
管理端口和服务端口不一致，无法工作

### ISSUE THREAD

**Issue by chinfeng2github** [weixiaohui-1/nacos-consul-adapter#2]
因为我 指定了和server.port不一样的管理端口

```
management:
  server:
    # 管理端点的端口
    port: 10002
```
这样在prometheus中配置的端口就是
```
  - job_name: 'prometheus-springcloud-gateway'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
    - server: gateway1:10002
      services: []

```
最后
https://github.com/chen-gliu/nacos-consul-adapter#%E7%89%B9%E6%80%A7
特性中四个接口 访问不到
